version: 1

cli:
  server: https://app.fossa.io
  fetcher: git
  project: github.com/launchdarkly/REPO_NAME
analyze:
  modules:
    - name: REPO_NAME
      path: .
      type: gradle
      options:
        task: dependencies