version: 2
jobs:
  build:
    docker:
      - image: circleci/java
      - image: redis
    steps:
      - checkout
      - run: cp gradle.properties.example gradle.properties
      - run: ./gradlew dependencies
      - run: ./gradlew test
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/;
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
  fossa:
    docker:
      - image: circleci/java
    steps:
      - checkout
      - run: cp gradle.properties.example gradle.properties
      - run: ./gradlew dependencies
      - run: curl https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
      - run: fossa analyze

workflows:
  version: 2
  test:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
      - fossa:
          filters:
            branches:
              ignore:
                - gh-pages